### ISSUE TITLE
New Algos

### ISSUE THREAD

**Issue by JLMirallesB** [malacalypse/h9-remote#2]
Hi malacalypse,
I'm trying to control my H9 max with an Arturia BeatStep and Ableton. And with your h9-remote everything works fine.
Also I'm developing a custom midi mapping set for fast change of multiple instances of your h9-remote scripts in live situation and also controlling any of the 10 parameters. I have done that with the help of remotify (now called Control Surface Studio), and I'm planning to write a little tutorial in my web explaining all the proces to do that.
I'm writing now to you for considering updating the h9-remote including the two new algos (Hotsawz and Harmadillo). If so, please contact me for including the update in the tutorial.
Thanks for the h9-remote!

**Comment by malacalypse** [comment]
Hi there, glad you're enjoying using it. I just updated it for HotSawz and Harmadillo. Let me know if you've got any issues with them, but on my H9 it seems to work just fine. Latest version is 1.1.3 now. Link back to your tutorial when you get it done, I'd love to see how you're utilizing the plugin.

**Comment by JLMirallesB** [comment]
Hi again! Thank you for the fast update. One last question. Maybe it’s an error when I configured the H9 pedal, but:

• when I move the expression value from a H9 preset, it moves perfectly inside the pedal, but  nothing changes in the H9 remote, so when I move again the knob value it moves from last knob value, not the actual “expression modified value” producing a “jump”

It’s a known issue or a error of mine?
Ps: I remember a problem configuring the H9, because the [XMT.CTL] was not there in the actual menu tree configuration. I will try to search more. Maybe that’s the problem.

---
José Luis Miralles
jlmirall.es

**Comment by JLMirallesB** [comment]
Hi, I didn’t find the XMT.CTL in the menu tree. Maybe the configuration of the H9 remote is with an old firmaware of the H9?

---
José Luis Miralles
jlmirall.es

**Comment by malacalypse** [comment]
Sorry, I don’t quite follow what you’re saying. 

Are you saying that when you change the expression value from the H9 (e.g. with a connected expression pedal) it doesn’t update the H9 Remote expression value? This would be because your H9 is for some reason not sending the expression CC for the H9 Remote to see. 

If you are saying also that the XMT.CTL option is no longer in the H9 firmware, I don’t know. Mine was setup with an older firmware and upgraded and it still sends CCs. I’ll see if I can reproduce your issue later on, but I won’t be back at the studio to play with it until the weekend likely. In the meantime, use a MIDI monitor and see if your pedal is sending CC when you change the expression value. If not, that’s your problem and you need to enable it to do that somehow. Perhaps Eventide has changed the firmware options without documenting it...

**Comment by malacalypse** [comment]
Ok, so they just renamed the control to XMT.CC in the latest versions (pre-HotSawz it was named XMT.CTL). Turn that on, and it should work fine.

**Comment by JLMirallesB** [comment]
Hi,
sorry for the delay.
I test the H9 and its expression pedal with a midi monitor (it sends the same via the pedal or via de hotknob). But I realized that the knobs which doesn’t move are only the knobs from the H9_remote window.
I’ll try to explain my best:

• I have the H9_remote and the H9 control app opened in the same computer.
    • When I move the expression pedal or the hotknob it takes effect only in the H9 control app and the h9; BUT not in the H9_remote.
    • When I move a knob in the H9_remote it takes effect in the H9 control app and the H9.
    • When I move the expression fader of the H9_remote it takes effect in the H9 control app and the H9; BUT not in the other 10 knobs of the H9-remote.
    • When I move anything in the H9 control app it doesn’t do nothing in the H9_remote (but i don't care about this scenario).

So, If i move the expression pedal, the values of the 10 knobs of the H9_remote are in the old position, and moving them from an external midi controllers produces a jump from the new ones. This is the problem….



---
José Luis Miralles
jlmirall.es

**Comment by malacalypse** [comment]
Ok, you have a lot going on here.

1. You cannot run the H9 Control app and the H9 Remote at the same time. They send conflicting information to the pedal and things get confused. The H9 Control software speaks an encrypted sysex to the H9 and tends to command exclusive control for some reason. I've had a lot of strange behaviour running it with anything else speaking MIDI to the H9, so this configuration is not supported or recommended.

Turn off H9 Control and reboot your H9 to put it out of custom sysex mode. 

2. In addition, the H9 pedal does not send CC in response to CC being sent to it - in other words if you have H9 Remote running and you're sending CC from another device to the H9 pedal, H9 Remote cannot see that CC as coming from the pedal and therefore will not track the position, because the pedal is not forwarding that data onwards.

If you want to use H9 Remote *and* control the pedal via another controller, you should map the other controller using MIDI learn in Live to the H9 Remote knobs. Then the 2-way sync between the H9 pedal and the H9 Remote will be uninterrupted.

The H9 is basically not intended to talk to more than one controlling device on MIDI at a time, if you want to maintain synchronized state, because of the way MIDI works - it's effectively a one-way data transmission. If controller A wants to know the state of device B, then B needs to update A with a CC message (as if it were controlling A!), then A can update its state to track B. But if you then change B's values with a second controller C, unless A can see the data that C is sending (and unless you're using a very complicated MIDI router/merger, this is usually never the case) then A will not update it's values to match. This is true for all MIDI devices, not just the H9.

**Comment by malacalypse** [comment]
Also, H9 Remote does not pretend to twiddle the knobs when you use the expression pedal (H9 Control is just pretending when you see the knobs move, that is completely for show and the actual values of the knobs do not change when you move the expression pedal - the pedal itself is computing the correct values for the effects). So don't expect to see the same fakery on H9 Remote, it's not for fancy graphics, it's for actual control of the H9 in a scriptable and repeatable manner.

**Comment by JLMirallesB** [comment]
Hi,

thank you a lot for the explanation.
So, for now I will try to keep things in a simple way.
I thing if I keep opened the H9 control app, but don’t move any knob with it, It doesn’t happens anything (I would like to have the H9 control app opened because I can see it bigger on the screen, than the max4live device). I’ll test it.
And I’ll assume that if I use and external expression pedal, I’ll lose the absolute positions of the H9 remote.
Maybe in a future I’ll try to do some MIDI wizardry to fix that.

Thank you again for the max4live device and also for the support by mail.

:)

---
José Luis Miralles
jlmirall.es

**Comment by JLMirallesB** [comment]
Hi again,
the problem with the expression pedal have and easy solution. Simply I assign a midi mapping to expression fader of the H9_remote from the external pedal, and it works. I can change the expression value by two inputs; the assigned knob from the external controler (always sending relative values) and from the external expression pedal (an H9-SP) always sending absolute (it will be a jump but not in every situation).
The only problem is using the knobs of the 10 parameters after moving the expression fader. If the H9_remote moved the 10 parameters (like the H9 control app) when moving the expression fader; then sending relative values to the 10 parameters will move them from the “expressioned” value and not from the initial value, but H9-remote don’t do that at the present, or it is very complicated to do, as you say.

---
José Luis Miralles
jlmirall.es

**Comment by malacalypse** [comment]
Are you saying your expression pedal is a MIDI pedal and not plugged into the H9? That's what I said before: if you're controlling it via external MIDI you need to map in LIVE using MIDI learn. If you're using a non-MIDI pedal plugged into the H9, it will work directly, as long as you have the XMT.CC and CTL.XMT settings correctly mapped to the plugin. 

I think you're unclear on the source of control for your expression pedal: if one pedal sends absolute values it will ALWAYS jump because that pedal is not tracking the current position of the control, which might be set by something else. That's how absolute values work. 

Again: I suggest that you should only and always control the H9 via ONE source - the H9 Remote. You can plug pedals directly into the H9 on the aux jack, but do not use MIDI pedals talking directly to the H9 or H9 Control. MIDI pedals and other MIDI controllers should be mapped inside Live to the H9 Remote controls using MIDI learn. That way the only way the H9 is controlled via MIDI is through H9 Remote, and that ensures that H9 Remote and the H9 pedal are always in sync.

As for the knob movement, since the H9 does not send the actual MIDI position of the knobs when the expression pedal is moved, that cannot be tracked. It is a technical limitation of the pedal's MIDI implementation - the data just isn't there. It would be very complicated to make a guess based on the mapping as to what the value "should" be and update the knobs, and I just don't have the time or inclination to get that fancy, and it would only ever be a guess, and still imprecise.

**Comment by malacalypse** [comment]
I also cannot say strongly enough: H9 Control does NOT play well with H9 Remote. They add confusing directives to the pedal and you WILL get strange behaviour from time to time. I do not recommend this and will not provide support for operating in this mode. You're on your own there, sorry!

**Comment by JLMirallesB** [comment]
Finally, the tutorial is out:

https://beyondthepiano.jlmirall.es/2019/08/14/eventide-h9-advanced-control-with-arturia-beatstep/

---
José Luis Miralles
jlmirall.es
