### ISSUE TITLE
psw switch

### ISSUE THREAD

**Issue by zspaceexplorer** [malacalypse/h9-remote#6]
sorry for double posting, not sure...

Hi I just try out your h9 m4l device. Its all working perfectly except for the psw switch. If I send the MIDI msg manually to the h9 like cc71 val 127 my h9 responds as expected. If I check the midi output of your plugin it sends the correct cc71 on the correct ch but the val is 0 instead of 127. How can I change that?

 thanks Falk

**Comment by malacalypse** [comment]
Depending on the algorithm your H9 is in, the switch either toggles or latches. Which algorithm are you in that you're finding the problem with?

**Comment by malacalypse** [comment]
To be further clear, the plugin sends both 127 and 0. If the switch is red, it sent 127, if it is grey, it sent 0. This follows the normal behaviour of a typical MIDI footswitch - push it and it sends 127, and if it is in latch mode, release does nothing, and pushing it again sends 0. If it is in toggle mode, releasing it immediately sends 0. Some Eventide algorithms (the ones from Timefactor and Modfactor) seem to behave most stably with one type of switch, the rest behave best with the other. If you're having trouble, try toggling the button less quickly - click it once and see if it does what you expect, then click again - the H9 seems to drop PSW messages that come too quickly, but behaves perfectly fine if they're spaced slightly further apart.

**Comment by zspaceexplorer** [comment]
Hi Daniel, 
thanks for your response. I have a h9max none of the algorithm respond to the psw switch. I made 2 videos to illustrate my problem, one with the setup of the h9 to verify its correct and one with the m4l device: http://www.grieffenhagen.de/h9setup.mov and http://www.grieffenhagen.de/h9m4l.mov
thanks for your help
Falk

**Comment by malacalypse** [comment]
I'll have to look into this. It works fine on both of my H9s, so I can't reproduce any issues with it so far. Give me a couple days to get back to the studio and try to reproduce what you're seeing.

**Comment by zspaceexplorer** [comment]
no Problem take your time. I am also rechecking with my 2nd h9 which I did w. version 1.1.3 without success, If I don´t write anything else it will be the same as Nr1

**Comment by zspaceexplorer** [comment]
Hi, 
I got a further update after exploring with my 2nd h9: the software on both h9 is 5.8.5, both work in the same way and are set up equally.
1. getting the settings from the device now works for some reason on both devices, sometimes I have to press the up arrow severals times after calling a h9 preset to update m4l , this is what I did not try before.
2. The psw switch will work for the pitch Factor Algorithms only, for no other algorithms on either h9. With the pitch Factor its sending 71 127 as expected, with the time Factor for example there is only 71 0 being sent to the h9. 
It Is correct that the psw cannot be automated via Midi? is it supposed to be done via hardware switch? If I send 71 127 differently via m4l the h9 respond as expected across all algorithms. As a workaround, this will work for me
thanks Falk

**Comment by malacalypse** [comment]
Ok, try this version see if it works for you (there was a bug for the Timefactor and Modfactor algorithms where it was only sending 0 - but it did not affect Pitchfactor, Space, or H9 algorithms). 

[H9 Remote 1.1.5.amxd.zip](https://github.com/malacalypse/h9-remote/files/4272769/H9.Remote.1.1.5.amxd.zip)

**Comment by malacalypse** [comment]
> It Is correct that the psw cannot be automated via Midi? is it supposed to be done via hardware switch?

I don't understand the question.

**Comment by zspaceexplorer** [comment]
Hi thanks for your effort, I can check the new version these days and will give feedback.
My question regarding the psw switch: I am using live and the h9 live on stage, so I am automating everything via midi. The psw button can not be assigned to a midi button whereas the button next to the "config" menu can be automated. I am using a MIDI foot controller and would like to assign a MIDI Msg to the psw switch or map it in a Audio Effect Rack. thanks Falk

**Comment by malacalypse** [comment]
Ah, I don't intend for this plugin to be used in a live context really. It's specifically for enabling session recall of the H9. All automation support is sort of a bonus thanks to the M4L components which permit it. Unfortunately the manner in which the PSW functions does not lend itself to tracking state between multiple simultaneous instances of the plugin which are managing the same H9 - which is the primary use case for this plugin (put it on a bunch of tracks even if you only have one H9, and then enable the instance you want to recall for overdubs, rework, etc. without needing the preset to be loaded on the pedal). Due to the "state" of that switch and the lack of feedback from the pedal as to whether it is "on" or "off" from the pedal's perspective (there is no data, MIDI or otherwise, that the pedal sends to indicate the current PSW state) I cannot keep it synchronized across the instances. So it does not make sense to permit it to be automated since it could be exactly out of sync (on when it thinks off, off when it thinks on). Since this is far worse than having to manually manage the one control that is least likely to be used when doing session recalls - and the most likely to be controlled directly on the pedal anyway! - I have decided not to support automating it. I would recommend you just pass that MIDI message straight through to the pedal, or better yet in your situation just using an external footswitch directly connected to it. I find the MIDI latency frustrating with that switch personally anyway and find it's implementation rather finicky - sometimes it doesn't get picked up properly by the pedal, sometimes it does but it latches opposite what I expect, etc. I've keyed the software to behave just like a manual MIDI footswitch would, but still there are problems in a performance context so for safety I would strongly suggest you try to make that be the one physical control you actually wire directly to the pedal, or send "out of band" directly via MIDI. It will remove a lot of potential problem points for you.

**Comment by zspaceexplorer** [comment]
Hi Daniel, 
Thanks for the Infos, I see you, use that software differently, but for me it´s still very usable if I use a computer in my stage setup. it works very nice with the push2. Btw: there is a hidden feature in Max to set the short_names of a slider via message, I tried to get the push2 displaying changing slider names but although the short_names change the push won´t update them correctly, thats probably the reason why the feature is hidden..
So now the version 1.1.5 works correct with the time Factor psw function here, the mod and the pitch also work but all the space and H9 algogrithms still have no psw function using the plugin. For me it´s fine to work with a footswich I can get all I need and I understand the point well why you are not implementing it. It would be helpful if Eventide would implementing sending the actual fader positions via MIDI. I suggested this years ago in the forum and also got an answer from Eventide that this might be a good idea and it´s not complicated to implement, but nothing happened so far, maybe one day...thanks for your help Falk

**Comment by malacalypse** [comment]
Hm, I cannot replicate your issue with the PSW on the Space or H9 - those work fine for me. Are you sure you have a mapping for the PSW on the given configuration you're using?

**Comment by malacalypse** [comment]
I'll consider this fixed for now and push 1.1.5 to the latest version.

**Comment by zspaceexplorer** [comment]
Hi Daniel, sorry for the late reply, you are right I did not do any mapping. I just compared the response sending a MIDI message from "outside" your M4L patch vs. from your patch just after dragging it into the slot. So if I do mapping it works and the time Algorithms now work as expected. Thanks for you work Falk

**Comment by malacalypse** [comment]
Hi Falk, 

Thanks for the feedback, glad it's working for you!
